# Generated by Django 5.0 on 2023-12-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedGraphType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_type', models.CharField(choices=[('line', 'Line Plot'), ('scatter', 'Scatter Plot'), ('box', 'Box Plot'), ('histogram', 'Histogram'), ('kde', 'KDE Plot'), ('violin', 'Violin Plot'), ('bar', 'Bar Plot'), ('heatmap', 'Heatmap'), ('pie', 'Pie Chart')], max_length=10)),
            ],
        ),
    ]
